stages:
  - init
  - test
  - finish

.deps:
  before_script:
    - cat schutzbot/team_ssh_keys.txt | tee -a ~/.ssh/authorized_keys > /dev/null
    - echo "Install packages utilities"
    - sudo dnf update -y && sudo dnf install -y dnf-plugins-core python3.10 python3-pip
    - echo "Install Terraform"
    - sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    - sudo dnf update -y && sudo dnf -y install terraform
    - echo "Install pip dependencies"
    - pip install -r requirements.txt
  variables:
    RUNNER: aws/fedora-35-x86_64
  tags:
    - terraform

.tests:
  extends: .deps
  after_script:
    - schutzbot/update_github_status.sh update || true
    - echo https://redhat.gitlab.io/-/services/products/image-builder/ci/cloud-image-val-ci/-/jobs/${CI_JOB_ID}/artifacts/report.html
  artifacts:
    paths:
      - report.html
    when: always

init:
  stage: init
  script:
    - schutzbot/update_github_status.sh start

aws:
  stage: test
  extends: .tests
  script:
    - AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" python3 cloud-image-val.py -r cloud/sample/resources_aws.json -d -p -m 'not pub' -o report.xml

azure:
  stage: test
  extends: .tests
  script:
    - ARM_CLIENT_ID="${AZURE_CLIENT_ID}" ARM_CLIENT_SECRET="${AZURE_CLIENT_SECRET}" ARM_SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID}" ARM_TENANT_ID="${AZURE_TENANT_ID}" python3 cloud-image-val.py -r cloud/sample/resources_azure_marketplace.json -d -p -o report.xml


finish:
  stage: finish
  script:
    - schutzbot/update_github_status.sh finish
