name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest test/

      - name: Get code coverage
        run: pytest --cov-report term-missing --cov=cloud/terraform --cov=result/ --cov=main/ --cov=test_suite/ test/

      - name: Python linter
        run: flake8 --ignore=E501

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: AWS
        run: |
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}  python3 cloud-image-val.py -r cloud/sample/resources_aws.json -d -p -o report.xml

      - name: Save report as artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: report.html
